[phases.setup]
aptPkgs = ["nginx", "curl", "procps", "findutils"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[phases.start]
cmd = "sh ./start.sh"

[start]
cmd = "sh ./start.sh"
