[phases.setup]
aptPkgs = ["nginx", "curl", "procps", "findutils"]
cmds = ["npm install -g lowdb json-server cors morgan"]

[phases.install]
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
cmds = ["npm run build"]

[phases.start]
cmd = "sh ./start.sh"

[start]
cmd = "sh ./start.sh"
